version: 2
jobs:
  build:
    working_directory: ~/mcumgr-android
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
           name: Configure Android SDK Licenses
           command: |
             mkdir "$ANDROID_HOME/licenses" || true
             echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
             echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
      - restore_cache:
          key: gradle-{{ checksum "settings.gradle" }}-{{ checksum "build.gradle" }}-{{ checksum "mcumgr-core/build.gradle" }}-{{ checksum "mcumgr-ble/build.gradle" }}
      - run:
          name: Android Assemble Debug
          command: >
                     ./gradlew
                     -PdisablePreDex
                     --max-workers 2
                     --no-daemon
                     --stacktrace
                     assembleDebug 
      #- run:
      #    name: Import GPG Files
      #    command: gpg --version && mkdir -p ~/.gnupg && echo "$SIGNING_PUBLIC_KEY_RING" | base64 --decode > ~/.gnupg/pubring.kbx && mkdir -p ~/.gnupg && echo "$SIGNING_TRUST_DB" | base64 --decode > ~/.gnupg/trustdb.gpg && echo "$SIGNING_SECRET_KEY_RING" | base64 --decode > ~/.gnupg/secring.gpg && gpg -K 0CFF1FF7 
      - run:
          name: Import GPG Keys
          command: export GPG_TTY=$(tty) && gpg --version && echo "$SIGNING_SECRET_KEY" | base64 --decode > ~/mcumgr-private.asc && gpg --import ~/mcumgr-private.asc && echo "$SIGNING_SECRET_KEY_PASSPHRASE" > ~/mcumgr-private-passphrase && gpg --batch --yes --pinentry-mode loopback --passphrase-file ~/mcumgr-private-passphrase --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg 
      - run:
          name: Deploy
          command: .circleci/deploy.sh
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "settings.gradle" }}-{{ checksum "build.gradle" }}-{{ checksum "mcumgr-core/build.gradle" }}-{{ checksum "mcumgr-ble/build.gradle" }}
      - run:
          name: Test
          command: ./gradlew test

